### PR TITLE
Aggregate Wats api

### PR DESCRIPTION
**Pull request by austinfromboston**
and the ability to interact with Wattle over an API.  Wow!

Added an AggregateWatsController that accepts multiple timescales to do periodic groupings
Allow users to set and reset API keys for themselves if they need API access

### CODE REVIEW

**Comment by cconstantine** [comment]
I'm a little worried about the lack of pagination.  'group by' in postgres is more expensive than you'd imagine (even indexed).  Have you tested this with the kind of data volume we have in production?

**Comment by austinfromboston** [comment]
Definitely not. Does paging at 1000 rows sound okay?  Hourly counts for the last 2 years would be 12k rows.

**Comment by austinfromboston** [comment]
Ok, made a 600k rows and a couple of clumps. I'm getting responses in about 2 seconds to the hourly query.  I owe you a dollar since JSON rendering is < 200 ms of that, the rest is ActiveRecord.  At that speed, I feel comfortable leaving pagination out for now, which simplifies the client code.  WDYT?

**Comment by austinfromboston** [comment]
Once I started writing the client, I realized I need more detail in the API data, like the app_name and app_env.  That slows down the query to 10 seconds.  With another couple of years of data, that could be unworkable.  Working on the pagination.

**Comment by austinfromboston** [comment]
adding a presenter object to format the data, also support pagination

**Comment by cconstantine** [comment]
I'm getting failures when I run rspec:
```
Failures:

  1) WatCounter#group groups the wats
     Failure/Error: expect(first_key[1]).to eq("demo")
       
       expected: "demo"
            got: "staging"
       
       (compared using ==)
     # ./spec/presenters/wat_counter_spec.rb:72:in `block (3 levels) in <top (required)>'

  2) AggregateWatsController#periodic when the request is daily should return an array of json counts
     Failure/Error: expect(demo_row['count']).to eq(5)
       
       expected: 5
            got: 10
       
       (compared using ==)
     # ./spec/controllers/aggregate_wats_controller_spec.rb:28:in `block (4 levels) in <top (required)>'

Finished in 1 minute 13.3 seconds (files took 3.39 seconds to load)
267 examples, 2 failures

Failed examples:

rspec ./spec/presenters/wat_counter_spec.rb:69 # WatCounter#group groups the wats
rspec ./spec/controllers/aggregate_wats_controller_spec.rb:24 # AggregateWatsController#periodic when the request is daily should return an array of json counts

Randomized with seed 56794
```

**Pull request merged**
